version: "3.9"

services:
  api:
    build: 
      context: ../api             # Sube a raíz y entra a api
      dockerfile: Dockerfile      # El archivo está ahí mismo en el contexto
    container_name: tarea_1_api
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: ${MONGO_URL}
      RABBIT_HOST: ${RABBIT_HOST}
    restart: always

  worker:
    build: 
      context: ../api
      dockerfile: Dockerfile
    container_name: tarea_1_worker
    command: python consumidor.py # Ejecuta el consumidor que está en /api
    environment:
      RABBIT_HOST: ${RABBIT_HOST}
    restart: always